// import mongoose from "mongoose";

// const subscriptionSchema = new mongoose.Schema(
//   {
//     tier: {
//       type: String,
//       enum: ["Basic", "Pro", "Enterprise"],
//       required: true,
//     },
//     price: {
//       type: Number,
//       required: true,
//     },
//     mac: {
//       type: String,
//       default: null,
//     },
//     key: {
//       type: String,
//       default: null, // initially null, generated by admin
//     },
//     hasLicenseKey: {
//       type: Boolean,
//       default: false,
//     },
//     keyExpiry: {
//       type: Date,
//       default: null,
//     },
//     users: [
//       {
//         type: mongoose.Schema.Types.ObjectId,
//         ref: "User",
//       },
//     ],
//   },
//   { timestamps: true }
// );

// const Subscription = mongoose.model("Subscription", subscriptionSchema);
// export default Subscription;
