import mongoose from "mongoose";

const userSchema = new mongoose.Schema(
  {
    email: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      trim: true,
    },
//    subscriptionIds:[
//     {
//       type: mongoose.Schema.Types.ObjectId,
//       ref: "Subscription",
//     }
//    ],
// requestedPlan:{
//     type: String, 
//     enum: ["Basic", "Pro", "Enterprise"],
//     default: null, // initially null, set when user requests a subscription
//   },
mac: {
      type: String,
      default: null,
    },
    key: {
      type: String,
      default: null, // initially null, generated by admin
    },
    hasLicenseKey: {
      type: Boolean,
      default: false,
    },
    keyExpiry: {
      type: Date,
      default: null,
    },
},

  { timestamps: true }
);

const User = mongoose.model("User", userSchema);
export default User;
